[package]
name = "my_wallet"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bip32 = "0.5.3"
bip39 = {version="2.2.2", features=["zeroize"]}
rand_core = {version="0.6.4", features=["getrandom"]}
zeroize = "1.8.2"
